name: CI
on: ["push", "pull_request"]

env:
  INFURA_KEY: ${{ secrets.INFURA_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "16.13.0"

      - name: Install Packages
        run: npm install

      - name: Run Tests
        run: npm run coverage

      - name: Codecov
        uses: codecov/codecov-action@master
        with:
          verbose: true
